apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-1z8b
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-1z8b
    app.kubernetes.io/part-of: tkrw-pr712-0075-0022-app
  name: devfile-sample-1z8b
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-1z8b
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-1z8b
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0022-tenant/tkrw-pr712-0075-0022-app/devfile-sample-1z8b@sha256:05fedf09926b3fbe0c6e14bc238c0c293f5bfa74523d41f31278fd9ec1c6982e
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
